name: 构建应用程序Windows_x64

# 控制工作流何时运行
on:
#   # 当 `push` 或 `pull request` 事件发生时就触发工作流的执行，这里仅仅针对 `master` 分支
#  push:
#    branches: [ main ]
#    tags:
#      - '*'
#   pull_request:
#     branches: [ main ]
# 允许用于在 `Actions` 标签页中手动运行工作流
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: build
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-2022]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v3
      with:
        #要使用的Python版本的版本范围或确切版本，使用SemVer的版本范围语法
        python-version: "3.9.13"
        #可选x64或x86。如果未指定，默认值为x64
        architecture: "x64"

    - name: Install dependencies
      run: |
        cd ./pyefun
        pip install -r requirements.txt
        python setup.py install
        pip install pyinstaller
        cd ..
        pip install -r requirements.txt
    - name: Build
      run: |
        pyinstaller QtEsayDesigner_window.spec
    #- name: Create Zip Package # 创建压缩包
    #  run: |
    #    zip -r ./dist/MacOS_ARM64.zip ./dist/app
    - name: Upload Artifact # 上传构建产物，这里我们的源码目录是根目录，而实际运行的代码是构建后的 dist 目录
      uses: actions/upload-artifact@v3
      with:
        name: Win_x64
        path: ./dist/QtEsayDesigner.exe # 上传 dist 目录下的 app 执行文件

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
#        tag: "latest"
        artifacts: "dist/*.exe"
        token: ${{ secrets.GITHUB_TOKEN }}


